export const TEAM_COUNTRY_CODES = {
  México: 'mx',
  Mexico: 'mx',
  Chequia: 'cz',
  Czechia: 'cz',
  'República Checa': 'cz',
  'Republica Checa': 'cz',
  Canada: 'ca',
  Canadá: 'ca',
  USA: 'us',
  'Estados Unidos': 'us',
  Brasil: 'br',
  Brazil: 'br',
  Corea: 'kr',
  'Corea del Sur': 'kr',
  'Korea Republic': 'kr',
  'South Korea': 'kr',
  Sudáfrica: 'za',
  Sudafrica: 'za',
  'South Africa': 'za',
  Francia: 'fr',
  France: 'fr',
  Senegal: 'sn',
  'Arabia Saudita': 'sa',
  'Saudi Arabia': 'sa',
  Portugal: 'pt',
  'RD Congo': 'cd',
  'DR Congo': 'cd',
  Congo: 'cd',
  Inglaterra: 'gb-eng',
  England: 'gb-eng',
  Escocia: 'gb-sct',
  Scotland: 'gb-sct',
  Gales: 'gb-wls',
  Wales: 'gb-wls',
  Croacia: 'hr',
  Croatia: 'hr',
  Ghana: 'gh',
  Suiza: 'ch',
  Switzerland: 'ch',
  Alemania: 'de',
  Germany: 'de',
  Italia: 'it',
  Italy: 'it',
  España: 'es',
  Espana: 'es',
  Spain: 'es',
  Argentina: 'ar',
  Uruguay: 'uy',
  Colombia: 'co',
  Japón: 'jp',
  Japon: 'jp',
  Japan: 'jp',
  Marruecos: 'ma',
  Morocco: 'ma',
  Australia: 'au',
  'Nueva Zelanda': 'nz',
  'New Zealand': 'nz',
  Qatar: 'qa',
  Catar: 'qa',
  Egipto: 'eg',
  Egypt: 'eg',
  Irán: 'ir',
  Iran: 'ir',
  Bélgica: 'be',
  Belgica: 'be',
  Belgium: 'be',
  PaísesBajos: 'nl',
  'Países Bajos': 'nl',
  'Paises Bajos': 'nl',
  Netherlands: 'nl',
  Holanda: 'nl',
  // Selecciones que faltaban (causaban fallback con siglas)
  Panamá: 'pa',
  Panama: 'pa',
  Uzbekistán: 'uz',
  Uzbekistan: 'uz',
  Noruega: 'no',
  Norway: 'no',
  Suecia: 'se',
  Sweden: 'se',
  Ecuador: 'ec',
  Paraguay: 'py',
  Austria: 'at',
  Argelia: 'dz',
  Algeria: 'dz',
  Túnez: 'tn',
  Tunez: 'tn',
  Tunisia: 'tn',
  Turquía: 'tr',
  Turquia: 'tr',
  Turkey: 'tr',
  Türkiye: 'tr',
  Irak: 'iq',
  Iraq: 'iq',
  Jordania: 'jo',
  Jordan: 'jo',
  Haití: 'ht',
  Haiti: 'ht',
  'Costa de Marfil': 'ci',
  "Côte d'Ivoire": 'ci',
  'Ivory Coast': 'ci',
  Curazao: 'cw',
  Curaçao: 'cw',
  Curacao: 'cw',
  'Cabo Verde': 'cv',
  'Cape Verde': 'cv',
  'Bosnia y Herzegovina': 'ba',
  'Bosnia and Herzegovina': 'ba',
  Bosnia: 'ba'
};

export function normalizeTeamName(teamName) {
  return String(teamName || '')
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .trim();
}

export function getTeamCountryCode(teamName) {
  if (TEAM_COUNTRY_CODES[teamName]) return TEAM_COUNTRY_CODES[teamName];
  const normalized = normalizeTeamName(teamName);
  const entry = Object.entries(TEAM_COUNTRY_CODES)
    .find(([name]) => normalizeTeamName(name) === normalized);
  return entry?.[1] || null;
}
